# 数据配置文件
# 包含数据路径、数据源和数据验证规则

# 数据路径配置
paths:
  # 输入数据路径
  documents_dir: './simplified_system/documents'
  survey_points_file: './simplified_system/data/导线点.csv'
  ground_truth_file: './simplified_system/data/ground_truth_annotations.csv'
  verification_file: './simplified_system/data/coordinate_verification_results.csv'
  
  # 输出数据路径
  output_dir: './simplified_system/output'
  experiment_output_dir: './simplified_system/experiment_results'
  
  # 日志路径
  log_dir: './simplified_system/logs'

# 数据源配置
data_sources:
  # 文档处理配置
  documents:
    supported_formats: ['.docx', '.doc', '.pdf']
    encoding: 'utf-8'
    max_file_size: '50MB'
    
  # 测量点数据配置
  survey_points:
    file_format: 'csv'
    encoding: 'utf-8-sig'
    delimiter: ','
    required_columns: ['点名', 'X', 'Y', 'Z']
    coordinate_system: 'CGCS2000'
    
  # 标注数据配置
  ground_truth:
    file_format: 'csv'
    encoding: 'utf-8-sig'
    required_columns: ['文档名称', '钻孔数量', '坐标成功数']
    
  # 验证数据配置
  verification:
    file_format: 'csv'
    encoding: 'utf-8-sig'
    required_columns: ['文档名称', '钻孔编号', '验证X', '验证Y', '验证Z']

# 数据验证规则
validation:
  # 钻孔数据验证
  drill_hole:
    hole_id:
      required: true
      pattern: '^[A-Za-z0-9\u4e00-\u9fa5]+$'  # 支持中英文数字
      max_length: 50
      
    depth:
      min: 0.0
      max: 5000.0
      unit: 'meter'
      
    azimuth:
      min: 0.0
      max: 360.0
      unit: 'degree'
      
    inclination:
      min: 0.0
      max: 90.0
      unit: 'degree'
      
    coordinates:
      x_range: [100000, 1000000]  # 适合中国境内坐标系
      y_range: [2000000, 5000000]
      z_range: [-1000, 10000]
      precision: 4  # 小数点后4位
      
    confidence:
      min: 0.0
      max: 1.0
      
  # 文档验证
  document:
    max_size_mb: 50
    min_content_length: 100
    required_sections: []
    
  # 坐标验证
  coordinate:
    tolerance_meters: 10.0
    min_confidence: 0.5
    coordinate_system_validation: true

# 数据清洗配置
data_cleaning:
  # 文本清洗规则
  text:
    remove_extra_whitespace: true
    normalize_numbers: true
    remove_special_chars: false
    min_line_length: 3
    
  # 数值清洗规则
  numeric:
    outlier_detection: true
    outlier_threshold: 3.0  # 标准差倍数
    fill_missing_strategy: 'none'  # none, mean, median, interpolate
    
  # 坐标清洗规则
  coordinate:
    duplicate_tolerance: 1.0  # 米
    invalid_coordinate_action: 'warn'  # warn, skip, error

# 数据转换配置
transformation:
  # 坐标系转换
  coordinate_system:
    input_crs: 'CGCS2000'
    output_crs: 'CGCS2000'
    transformation_accuracy: 'high'
    
  # 单位转换
  units:
    depth: 
      input: 'meter'
      output: 'meter'
    angle:
      input: 'degree'
      output: 'degree'
    coordinate:
      input: 'meter'
      output: 'meter'

# 数据备份配置
backup:
  enabled: true
  backup_dir: './simplified_system/backup'
  retention_days: 30
  backup_schedule: 'daily'  # daily, weekly, monthly
  compress: true
  
  # 备份内容
  include_patterns:
    - '*.csv'
    - '*.json'
    - '*.yaml'
    - '*.log'
  
  exclude_patterns:
    - '*.tmp'
    - '*.temp'
    - '__pycache__'

# 数据质量监控
quality_monitoring:
  enabled: true
  
  # 质量指标
  metrics:
    completeness_threshold: 0.95
    accuracy_threshold: 0.90
    consistency_threshold: 0.95
    
  # 异常检测
  anomaly_detection:
    enabled: true
    algorithms: ['isolation_forest', 'statistical']
    sensitivity: 0.1
    
  # 质量报告
  reporting:
    generate_reports: true
    report_format: ['json', 'html']
    report_schedule: 'weekly'